name: Main

on: [push]

jobs:
  actiontrigger:
    runs-on: ubuntu-latest
    name: Action Trigger
    steps:
    # To use this repository's private action, you must check out the repository
    - name: Checkout
      uses: actions/checkout@v2
    - name: Action Trigger Step
      id: action-trigger-step
      uses: ./.github/actions/test-action
    - name: Use output
      run: echo "The output was ${{ steps.action-trigger-step.outputs.some-secretvalue }}"